
version: "3.9"

services:
  db:
    image: iscra56/tasklite-db:1.0
    container_name: tasklite-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  backend:
    image: iscra56/tasklite-api:1.1
    container_name: tasklite-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-net
      - frontend-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  frontend:
    image: iscra56/tasklite-ui:1.1
    container_name: tasklite-ui
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

networks:
  frontend-net:
  backend-net:

volumes:
  db_data:
