apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tasklite-project
  namespace: argocd
spec:
  description: "Zabezpieczony projekt ArgoCD dla aplikacji TaskLite"

  sourceRepos:
    - '*' 

  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: tasklite
