apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasklite-app
  namespace: argocd
spec:
  project: tasklite-project

  source:
    repoURL: 'https://github.com/Dripson02/Sprawozdanie2_CICD.git'
    targetRevision: HEAD
    path: manifests 

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tasklite

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
